### ISSUE TITLE
Download button downloads .zip file

### ISSUE THREAD

**Issue by oyvindeide** [equinor/everviz#114]
Would be good to have .csv straight away?

**Comment by DanSava** [comment]
Yes, I think it would be good to have CSV straight away. Or at least have an option between ZIP and raw CSV.

I implemented the direct CSV download on the Everviz side but it was impossible to trigger from the download data button of the webviz container.   

The only sane way to solve this is to make a PR with changes in https://github.com/equinor/webviz-core-components that would support a data frame download and also one in https://github.com/equinor/webviz-config to add a new button to the list of buttons that can be displayed.

**Comment by oyvindeide** [comment]
We should start by reaching out to the developers of `webviz` to get their thoughts on the issue.
