### ISSUE TITLE
Disable/put warning on statistics if there are few realizations

### ISSUE THREAD

**Issue by oyvindeide** [equinor/everviz#117]
If there are very few realizations the statistics button might not make that much sense, and we should perhaps warn the user that it is not statistically significant.

**Comment by DanSava** [comment]
What statistics button are we going to target? All the statistics/data radio buttons in the objectives, summary values and well rates plots? or just one of them? If so which one?

Also what are too few realizations? 5? 3? 

How should the warning be added? 
- As a text next to the button?
- Don't show any warning but disable the radio option if there are too few realizations
- When hovering over the button?
- When clicking the button as an alert dialog?

**Comment by oyvindeide** [comment]
> Also what are too few realizations? 5? 3? 

Starting point should be to show the notice regardless, and show how many realizations form the basis for the statistics calculation.
