### ISSUE TITLE
Change default name of screenshot

### ISSUE THREAD

**Issue by oyvindeide** [equinor/everviz#118]
Might be good to update the default name of the screenshot, for example <config_name>.png, or perhaps also date stamp?

**Comment by DanSava** [comment]
Only possible by updating `WebvizPluginPlaceholder` in https://github.com/equinor/webviz-core-components

**Comment by DanSava** [comment]
Currently, WebvizPluginPlaceholder has hardcoded the filename `webviz-screenshot.png` should be updated to support a given filename.

**Comment by oyvindeide** [comment]
Will you create an issue with webviz? If it is easy to fix we could propose a patch?

**Comment by DanSava** [comment]
I have been looking at the `webviz-core-components` code a bit I think it would be feasible and fun to propose a patch.

**Comment by DanSava** [comment]
Made https://github.com/equinor/webviz-core-components/issues/63 and also the proposed patch https://github.com/equinor/webviz-core-components/pull/64 that should allow Everviz to change the filename of the screenshot the core component saves. 

Should be also followed by changes in `webviz-config` as well that would expose the same functionality in https://github.com/equinor/webviz-config/blob/master/webviz_config/_plugin_abc.py

**Comment by oyvindeide** [comment]
What is the status of this? See that you got you PR merged, do we need to add a PR to `webviz-config`?

**Comment by DanSava** [comment]
I think it was possible to use the functionality without also exposing it in `webviz-config`

But to make it more clear a PR should be added in `webviz-config`

**Comment by oyvindeide** [comment]
We should reach out to the developers of `webviz` to see about implementing this possibility.

**Comment by DanSava** [comment]
https://github.com/equinor/webviz-config/pull/269 was merged in webviz-config and will probably be available in the new release. 

Now the question remains should we name the screenshot file names differently for each of the plugins everviz creates or is it acceptable to have a general name?

**Comment by DanSava** [comment]
When for the general naming approach. Now when the user will download the screenshot. The filename that will be download will have the name as follows `everviz_plugin_name.png`, e.g `everviz_objectives_plot.png`
