### ISSUE TITLE
Plot colors do not change by batch or date in the summary plot

### ISSUE THREAD

**Issue by verveerpj** [equinor/everviz#131]
In the summary plot, key values can be plotted for multiple batches, or for multiple dates. Different keywords are plotted in different colors, but different dates or summary values are not. This makes it difficult to distinguish the plots visually.

To reproduce: select "Summary Values" and add plots using "Batches to plot" or "Dates to plot"

**Comment by DanSava** [comment]
I am guessing this is only when selecting statistics because the colors seem to be different when looking at the raw data. 
![Screenshot from 2020-09-02 09-04-28](https://user-images.githubusercontent.com/4508053/91937778-5ed22c00-ecfb-11ea-9661-0e505275b64d.png)
