### ISSUE TITLE
Min/max plot

### ISSUE THREAD

**Issue by oyvindeide** [equinor/everviz#133]
Create a radio button to show the min/max and mean values in addition to statistics and raw data. The min and max are the highest and lowest realization (final data point in the objective function evaluation).

**Comment by markusdregi** [comment]
The min/max plot is a time series plot for a specific iteration. The min and max realisation is picked as the two realisations with the lowest and highest objective function value in that iteration respectively. This implies that for one iteration, all data displayed in the max (or min) plot will come from the same realisation. However, for two different iterations, the data for max might be coming from two different realisations...
