### ISSUE TITLE
Plot different keywords using second axis

### ISSUE THREAD

**Issue by sondreso** [equinor/everviz#140]
Users would like to plot different keywords together in the same plot, using a second axis.

First step Investigate if webviz support this

**Comment by DanSava** [comment]
Investigated if we can support multiple axis and as Peter was saying during the planning meeting,  Plotly supports that hence also Everviz can support it. 

But I could not find any way of displaying the y-axis ranges and titles without them overlapping when the user tries to compare more than 2 summary keys.
