### ISSUE TITLE
Highligth which batch is the optimal one

### ISSUE THREAD

**Issue by sondreso** [equinor/everviz#141]

**Comment by verveerpj** [comment]
It is somewhat unclear what is exactly wanted, and if it is necessary. 

Currently, in the objective function plot, the accepted batches are already highlighted in red, the last one should indicate the best accepted batch.

Is it necessary to highlight the last accepted point differently?

**Comment by sondreso** [comment]
Waiting for feedback from users

**Comment by DanSava** [comment]
Closing, for now, still no feedback received from user.
