### ISSUE TITLE
The snapshots dot not work as expected for the second plot on the page. 

### ISSUE THREAD

**Issue by DanSava** [equinor/everviz#143]
**Issue**

If an everviz page contains two plots i.e Objectives, Summary values, Controls page when scrolling to the button of the page and trying to save the screenshot for the second plot. The image saved to disk is incomplete 
![controls](https://user-images.githubusercontent.com/4508053/93784350-97e42900-fc35-11ea-942d-8d2544033a3d.png)

the x-axis from the plot is missing.

**Comment by verveerpj** [comment]
This appears to be a webviz issue, I could reproduce it with their online demo. I reported this on the webviz slack channel.

**Comment by anders-kiaer** [comment]
Will be fixed when https://github.com/equinor/webviz-core-components/pull/75 is merged + released.

**Comment by DanSava** [comment]
Seems that equinor/webviz-core-components#75  was merged and released. 

Closing this issue.
