### ISSUE TITLE
Plot snapshots should only contain the plot image. 

### ISSUE THREAD

**Issue by DanSava** [equinor/everviz#144]
Currently, when saving a plot screenshot the image saved to disk contains also labels and dropdowns used to generate the plot. 
![everviz_objectives_plot (1)](https://user-images.githubusercontent.com/4508053/93785147-6c157300-fc36-11ea-9188-8f1d2527643e.png)

If possible saved screenshot should contain only the graph from the right part of the image above without the dropdown and radio buttons from the left.

**Comment by verveerpj** [comment]
Requires changes in webviz. Contacted the developers who made an issue, so we wait for that.

**Comment by anders-kiaer** [comment]
`blob:` in `img-src` now allowed in latest release https://github.com/equinor/webviz-config/releases/tag/0.2.0
