### ISSUE TITLE
Support portable option

### ISSUE THREAD

**Issue by DanSava** [equinor/everviz#153]
**Issue**
It is time-consuming to re-build every time. Investigate the possibility to support the portable option?

**Comment by sondreso** [comment]
We should look into options for speeding this up. (Test out portable, might be the CSV). Not a major issue, can be postponed beyond TRL7.

**Comment by oyvindeide** [comment]
We looked into the portal option, and it will probably not be a good solution in this case. While it will speed up the second start for webviz, it does come at a cost. Currently what happens at the start up of `everviz` is that a server is created by `webviz` and `everest`, `everest` then exports the data (which is part of the reason the start-up is a bit slow) to a file. This file is given to `webviz`. If we run this in portable mode the user would manually have to export the data for each run as it would not automatically be updated, and keeping things in sync would quickly become difficult.
