### ISSUE TITLE
Summary values as a function of batch, visiblity

### ISSUE THREAD

**Issue by oyvindeide** [equinor/everviz#159]
When data (as opposed to statistics) is selected the legend does not correlate to the colors in the graph. We should:
1) remove the legend (or even better, show the (empty) glyph for each date)
2) use different glyphs for different dates

**Comment by markusdregi** [comment]
A good start is probably to run Everest and use everviz to visualise the the summary vectors of a multi-batch case.

**Comment by kabrus** [comment]
[Summary values as a function of batch.pptx](https://github.com/equinor/everviz/files/8254359/Summary.values.as.a.function.of.batch.pptx)
