### ISSUE TITLE
Summary values as function of date

### ISSUE THREAD

**Issue by oyvindeide** [equinor/everviz#161]
The plot can have multiple y-axis, sometimes overlapping, which can make the plot hard to read. We can look into removing multiple y-axis, or try to implement some logic on top of the current implementation.

**Comment by markusdregi** [comment]
It might be a possible solution to limit the number of plots to two.

**Comment by kabrus** [comment]
[Summary values as a function of date - multiple axis.pptx](https://github.com/equinor/everviz/files/8254436/Summary.values.as.a.function.of.date.-.multiple.axis.pptx)
