### ISSUE TITLE
Gradient vs controls plot

### ISSUE THREAD

**Issue by oyvindeide** [equinor/everviz#162]
If there are a lot of controls the plot will quickly become hard to read. Add dropdown to filter on controls, which defaults to all controls.

**Comment by markusdregi** [comment]
**Main goal**
To ease adding (almost all) or a single plot it would be neat to have the possibility of:
- selecting all and 
- emptying the list of controls visualised.

**Secondary goal (if feasible)**
Make it possible select all matches for a filter.

**Comment by kabrus** [comment]
[Gradient values.pptx](https://github.com/equinor/everviz/files/8254462/Gradient.values.pptx)
