### ISSUE TITLE
Use different symbols for different summary keys 

### ISSUE THREAD

**Issue by DanSava** [equinor/everviz#166]
**Issue**

For Summary Values and the Well rates pages when selecting `Data`  radio button the plots should use different symbols for each of the summary keys selected (ex assume user-selected FOPT and FWPT as summary keys, the plots should use `circles` for FOPT and `square` or `stars` for FOWPT as symbols for each data point displayed)

**Comment by berland** [comment]
I don't know how an example plot looks like in this context, but I would at first hand think of separating these with colours instead of markers? If the time-resolution is fine, the markers will probably obfuscate each other.

**Comment by DanSava** [comment]
The issue is a bit outdated. I will close it for now and open a new one if this is still required going forward.
