### ISSUE TITLE
Rename data_path to csv_file

### ISSUE THREAD

**Issue by oyvindeide** [equinor/everviz#42]
Should consider renaming the `data_path` argument to `csv_file` to be more in tone with ´webviz-config`?
https://github.com/equinor/everviz/blob/f33cd3f204d0abc17b4bbc80fcf68e4c3942b4c8/everviz/plugins/crossplot/crossplot.py#L21

On the other hand, we want to go away from disk operation in the long run, so might not be worth it?

**Comment by DanSava** [comment]
Even if we will go away from disk operations in the long run. I don't think it is a bad idea to try to be consistent with `webviz` plugin examples.

**Comment by verveerpj** [comment]
I agree. But in this context, in the pull request that I made most recently, I use two csv files in the plugin, so there it breaks already...
