### ISSUE TITLE
In the Objectives plot only show non-gradient objective values for each geo-realization

### ISSUE THREAD

**Issue by DanSava** [equinor/everviz#57]
**Issue**

* For cases with few geo-realization we should consider either setting the radio button to data in place of statistics as the default. 

* Or just use data as the default always

Blocked by: https://github.com/equinor/everest/pull/1271

**Comment by oyvindeide** [comment]
We could set data as the default and only allow statistics if there are enough data points, but where do we set the threshold? I´m guessing that in many cases there won´t be enough geo-realizations to be statistically significant. The user might expect in anyway though.

**Comment by oyvindeide** [comment]
Do you have an opinion here @DanSava or @verveerpj? Can disable the statistics button if there are not enough data going into the statistics calculation, or just simply make `Data` the default option.

**Comment by verveerpj** [comment]
> Do you have an opinion here @DanSava or @verveerpj? Can disable the statistics button if there are not enough data going into the statistics calculation, or just simply make `Data` the default option.

I would not disable, because people would wonder where the option went. Switching to data when the number of points is too low makes sense.
