### ISSUE TITLE
Not working screenshot

### ISSUE THREAD

**Issue by oyvindeide** [equinor/everviz#71]
Screenshot is seemingly broken? Confirm that it works

**Comment by DanSava** [comment]
locally (not RGS) it works just fine.

**Comment by oyvindeide** [comment]
Sounds good, I`ll quickly confirm that it works on RGS.

**Comment by DanSava** [comment]
Made new issue (#75) with a bit more details, should have updated this one instead :disappointed: . Closing this one.
