### ISSUE TITLE
Visualize permutations - well order

### ISSUE THREAD

**Issue by oyvindeide** [equinor/everviz#73]
We would like to visualise permutations dictated by control variables. However, visualising permutations are non-trivial, especially if the development over iterations are taken into account.

**Comment by DanSava** [comment]
This will require us to be able to extract what type of optimization experiment we are trying to display data for, and I am not sure how this will conflict with the idea that Everest is a "general" optimizer.

**Comment by oyvindeide** [comment]
Closing this because there is an over arching issue relating to getting data from the forward models, which needs to be solved first https://github.com/equinor/everest/issues/1309
