### ISSUE TITLE
Objective values plots, track geo realizations

### ISSUE THREAD

**Issue by DanSava** [equinor/everviz#77]
During the user visualization meeting, there was a discussion regarding the objective plots, some users wanted labeled realizations to track geo realizations, or potentially drawn lines instead of scattered points, potentially have geo realization filter.

Some discussion regarding what is the right approach is still needed.

**Comment by kabrus** [comment]
Hi! OK to track realisations I think, but I would prefer lines instead of scatter plots, but maybe rather "strippled"/weak color lines so that it doesn't potentially look to messy?

**Comment by oyvindeide** [comment]
Sounds good, we can start with that, always possible to change in the future. An option could also be some user customization (lines on/off for example)
