### ISSUE TITLE
Suggestions for visualising orderings

### ISSUE THREAD

**Issue by markusdregi** [equinor/everviz#89]
We should collect some ideas for how to visualise #73

**Comment by DanSava** [comment]
Simple Gantt chart for the wells in a possible drill plan.

![Screenshot from 2020-06-26 11-34-29](https://user-images.githubusercontent.com/4508053/85837785-37159380-b7a1-11ea-87f3-1a09b91ec65a.png)

**Comment by DanSava** [comment]
Drill plan where wells are ordered by drill start date

![Screenshot from 2020-06-26 12-13-52](https://user-images.githubusercontent.com/4508053/85841335-a346c600-b7a6-11ea-967f-1a0c70c1edad.png)

**Comment by DanSava** [comment]
Another possibility would be to display the drill order grouped by rig:
 
![Screenshot from 2020-06-26 12-21-42](https://user-images.githubusercontent.com/4508053/85842021-a4c4be00-b7a7-11ea-827c-24c602625595.png)

**Comment by oyvindeide** [comment]
Releated to https://github.com/equinor/everest/issues/1309, not really possible to do at the moment, closing.
