### ISSUE TITLE
Investigate if it is possible to export all the available plots at once

### ISSUE THREAD

**Issue by DanSava** [equinor/everviz#90]

**Comment by verveerpj** [comment]
I am having trouble finding a way to do this easily. Currently, each plot has a screenshot button, which you can disable from webviz, but I don't see how access the underlying code it calls. It seems to be a dash/plotly feature, but I could not find any hints how to use it.

Of course, you can save plots that you generate, so it is feasible to generate all the plots and save them. However, this would require extending each plugin to do that, in a way that respects the settings that the user made. This could be an extensive job, and therefore we should ask ourselves if this is a priority.

For this reason, moving it back to Todo, with label question, the question begin, is this worth pursuing?

**Comment by oyvindeide** [comment]
I vote for closing, we can create a new issue if anyone really misses that feature. I would imagine that would be in the form of some auto report generator, so will probably require quite a bit of work.

**Comment by verveerpj** [comment]
I also think it should be closed. In particular I agree that this feature is going towards making a report generator, something we should think more carefully about, if that should be done at all in the context of everviz. I will close this issue.
